
services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=stude_mgmt
    ports:
      - "3306:3306"
    restart: always

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+aiomysql://root:password@db:3306/stude_mgmt
      - SECRET_KEY=raqa-45yetQwa-8hgybhskalmdhinAkar8*kga9tr
    depends_on:
      - db
    restart: always

volumes:
  mysql_data:
